function wmvWindow

% wmvWindow: constructs the WMV window when the Remora is called
%
% This script is called whenever WMV is activated from the Triton control
% window. 
%
% Adapted from lt_init_lVis_window by Michaela Alksne and Shane Andres

    global REMORA HANDLES PARAMS
    
    defaultPos = [0.1,0.1,0.3,0.20];
    
    if isfield(REMORA.fig, 'lt')
        % check if the figure already exists. If so, don't move it.
        if isfield(REMORA.fig.lt, 'lVis_settings') && isvalid(REMORA.fig.lt.lVis_settings)
            defaultPos = get(REMORA.fig.lt.lVis_settings,'Position');
            return;
        else
            REMORA.fig.lt.lVis_settings = figure;
        end
    else
        REMORA.fig.lt.lVis_settings = figure;
    end
    
    % initializing the current edit to blank (needed for editBoundingBox)
    REMORA.lt.lVis_det.currentEdit = [];
    % indicate current window is for loading existing labels
    REMORA.lt.lVis_det.newFile = false;
    % importing any project-specific settings
    config;

    set(REMORA.fig.lt.lVis_settings,'NumberTitle','off', ...
        'Name','Visualize Labels',...
        'Units','normalized',...
        'MenuBar','none',...
        'Position',defaultPos, ...
        'Visible', 'on',...
        'ToolBar', 'none');
    
    figure(REMORA.fig.lt.lVis_settings)
    


    % callback to handle WMV close button press
    function closeWMV(src, event)

        % check if there are any unsaved edits
        if isfield(REMORA.lt.lVis_det, 'dataTable') && isfield(REMORA.lt.lVis_det, 'dataTableSaved')
            data = table2cell(sortrows(REMORA.lt.lVis_det.dataTable,'start_time'));
            dataSaved = table2cell(sortrows(REMORA.lt.lVis_det.dataTableSaved,'start_time'));

            % show popup if edits are not saved
            if ~isequaln(data, dataSaved) 
                % ask user to confirm exit
                choice = questdlg('Unsaved changes - do you want to exit?', ...
                                  'Confirm Exit', ...
                                  'Exit', 'Cancel', 'Cancel');
                % handle response
                switch choice
                    case 'Cancel'
                        return;        
                end
            end
        end

        % delete stored file path to detections
        if isfield(REMORA.lt.lVis_det, 'fileFullPath')
            REMORA.lt.lVis_det = rmfield(REMORA.lt.lVis_det, 'fileFullPath');
        end

        % delete (extra) cached version of detections
        if isfield(REMORA.lt.lVis_det, 'dataTableSaved')
            REMORA.lt.lVis_det = rmfield(REMORA.lt.lVis_det, 'dataTableSaved');
        end

        delete(src);
        plot_triton;
        return;
        
    end
    set(REMORA.fig.lt.lVis_settings, 'CloseRequestFcn', @(src, event) (closeWMV(src, event)));
    
    
    
    %%%%button grid
    row = 7;
    col = 3;
    h = 1/row;
    w = 1/col;
    x = 0:w:1;
    y = 1:-h:0;
    xbuff = w*0.25;
    ybuff = h*0.2;
    
    %%%colors
    bgColor = [1 1 1];
    bgColorPurple = [0.8 0.6 0.6];
    bgColorTeal = [0.2 0.6 0.4];
    bgColorGreen = [0.6 0.8 0.6];
    bgColorCoral = [1.0 0.6 0.4];
    bgColorBlue = [0 0.8 1.0];
    REMORA.lt.lVis_verify = [];
    
    %% title content
    btnPos = [x(1) y(2) w h];
    labelStr = 'Load predictions to visualize';
    REMORA.lt.lVis_verify.headtext = uicontrol(REMORA.fig.lt.lVis_settings, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',btnPos, ...
        'String',labelStr, ...
        'FontUnits','points', ...
        'FontWeight','bold',...
        'FontSize',10,...
        'Visible','on');  %'BackgroundColor',bgColor3,...
    
    %%work with rawFile -all set to on right now for ease
    % if REMORA.lt.lVis_params.rawFile
    f_enableRF = 'on'; %get(HANDLES.motion.fwd,'Enable');
    next_enableRF = 'on'; %get(HANDLES.motion.nextfile,'Enable');
    b_enableRF = 'on'; %get(HANDLES.motion.back,'Enable');
    prev_enableRF = 'on'; %get(HANDLES.motion.prevfile,'Enable');
    ref_enable = 'on'; %refresh button always enabled
    % else
    %     f_enableRF = 'off';
    %     b_enableRF = 'off';
    %     next_enableRF = 'off';
    %     prev_enableRF = 'off';
    % end
    
    
    %% label loading functionality
    labelStr = 'Load WMD Predictions';
    btnPos=[x(1) y(2) w h];
    REMORA.lt.lVis_verify.load1 = uicontrol(REMORA.fig.lt.lVis_settings,...
        'Style','pushbutton',...
        'Units','normalized',...
        'String',labelStr,...
        'Position',btnPos,...
        'FontUnits','normalized', ...
        'Enable', 'on', ...
        'Callback','wmvControl(''LoadLabels'')');
    
    
    %% display label buttons
    labelStr = '...';
    btnPos = [x(2)+xbuff y(2) w*1.3 h];
    REMORA.lt.lVis_labels.label1Check = uicontrol(REMORA.fig.lt.lVis_settings,...
        'Style','checkbox',...
        'Units','normalized',...
        'String',labelStr,...
        'Position',btnPos,...
        'Value',0,...
        'Enable', 'off', ...
        'FontUnits','normalized', ...
        'Callback','wmvControl(''Display'')');
    
    %% Add detections
    
    % Add a button for "Add Detection" in the main figure
    labelStr = 'Add Detection';
    btnPos = [x(2)-w/2 y(4) - 3*ybuff 2*w 2*h];
    REMORA.lt.lVis_labels.addDetection = uicontrol( ...
        'Style', 'pushbutton', ...
        'Units','normalized',...
        'String', labelStr, ...
        'FontUnits','normalized', ...
        'Position', btnPos, ... 
        'BackgroundColor',bgColorGreen,...
        'Callback', 'wmvControl(''AddDetection'')');

    %% back button
    labelStr = '<';
    btnPos = [x(1)+w/2 y(6)-ybuff w h];
    REMORA.lt.lVis_labels.RFback = uicontrol(REMORA.fig.lt.lVis_settings,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColorCoral,...
        'String',labelStr ,...
        'FontUnits','normalized', ...
        'Enable', b_enableRF, ...
        'FontWeight','bold',...
        'Callback','wmvControl(''SmallStepBack'')');
    
    %% forward button
    labelStr = '>';
    btnPos = [x(2)+w/2 y(6)-ybuff w h];
    REMORA.lt.lVis_labels.RFfwd = uicontrol(REMORA.fig.lt.lVis_settings,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColorCoral,...
        'String',labelStr ,...
        'FontUnits','normalized', ...
        'Enable', f_enableRF, ...
        'FontWeight','bold',...
        'Callback','wmvControl(''SmallStepForward'')');
    
    %% prev detection button
    labelStr = 'Prev';
    btnPos = [x(1) y(6)-ybuff w/2 h];
    REMORA.lt.lVis_labels.prevF = uicontrol(REMORA.fig.lt.lVis_settings,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColorCoral,...
        'String',labelStr ,...
        'FontUnits','normalized', ...
        'Enable', prev_enableRF, ...
        'FontWeight','normal',...
        'Callback','wmvControl(''PrevDetection'')');
    
    %% next detection button
    labelStr = 'Next';
    btnPos = [x(2)+1.5*w y(6)-ybuff w/2 h];
    REMORA.lt.lVis_labels.nextF = uicontrol(REMORA.fig.lt.lVis_settings,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColorCoral,...
        'String',labelStr ,...
        'FontUnits','normalized', ...
        'Enable', next_enableRF, ...
        'FontWeight','normal',...
        'Callback','wmvControl(''NextDetection'')');
    
    %% save edits to file
    labelStr = 'Save Edits';
    btnPos = [x(1)+w/2 y(7)-2*ybuff w h];
    REMORA.lt.lVis_labels.refresh = uicontrol(REMORA.fig.lt.lVis_settings,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColorBlue,...
        'String',labelStr ,...
        'FontUnits','normalized', ...
        'Enable', ref_enable, ...
        'FontWeight','normal',...
        'Callback','wmvControl(''SaveEdits'')');

     %% make new training examples
     labelStr = 'Make New Examples';
     btnPos = [x(2)+w/2 y(7)-2*ybuff w h];
     REMORA.lt.lVis_labels.refresh = uicontrol(REMORA.fig.lt.lVis_settings,...
         'Style','pushbutton',...
         'Units','normalized',...
         'Position',btnPos,...
         'BackgroundColor',bgColorBlue,...
         'String',labelStr ,...
         'FontUnits','normalized', ...
         'Enable', ref_enable, ...
         'FontWeight','normal',...
         'Callback','wmvControl(''makeNewExamples'')');
    
    %% move to previous file in folder
    labelStr = 'Previous File';
    btnPos = [x(1) y(7)-2*ybuff w/2 h];
    REMORA.lt.lVis_labels.refresh = uicontrol(REMORA.fig.lt.lVis_settings,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColorCoral,...
        'String',labelStr ,...
        'FontUnits','normalized', ...
        'Enable', ref_enable, ...
        'FontWeight','normal',...
        'Callback','wmvControl(''LoadPrev'')');
    
    %% move to next file in folder
    labelStr = 'Next File';
    btnPos = [x(3)+w/2 y(7)-2*ybuff w/2 h];
    REMORA.lt.lVis_labels.refresh = uicontrol(REMORA.fig.lt.lVis_settings,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColorCoral,...
        'String',labelStr ,...
        'FontUnits','normalized', ...
        'Enable', ref_enable, ...
        'FontWeight','normal',...
        'Callback','wmvControl(''LoadNext'')');

end
